image: "gableroux/unity3d:2017.4.27f1"

stages:
- build_and_test

variables:
  BUILD_NAME: RubeGoldberg
  PROJECT_PATH: RubeGoldberg

.unity_before_script: &unity_before_script
  before_script:
  - chmod +x ./ci/before_script.sh && ./ci/before_script.sh

.cache: &cache
  cache:
    key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$TEST_PLATFORM"
    paths:
      - ./RubeGoldberg/Library/

.test: &test
  stage: build_and_test
  <<: *unity_before_script
  <<: *cache
  script:
  - chmod +x ./ci/test.sh && ./ci/test.sh
  artifacts:
    paths:
    - $(pwd)/$TEST_PLATFORM-results.xml

# run this when you need to request a license again
# you will need to follow activation steps from documentation
# Look at the logs and grab the XML
get-license:
  when: manual
  stage: build_and_test
  <<: *cache
  script:
    - chmod +x ./ci/get_license.sh && ./ci/get_license.sh

# test-editmode:
#   <<: *test
#   variables:
#     TEST_PLATFORM: editmode

# test-playmode:
#   <<: *test
#   variables:
#     TEST_PLATFORM: playmode

.build: &build
  stage: build_and_test
  <<: *unity_before_script
  <<: *cache
  script:
  - chmod +x ./ci/build.sh && ./ci/build.sh

  artifacts:
    paths:
    - ./Builds
  # only:
  #   - master

build-StandaloneWindows64:
  <<: *build
  variables:
    BUILD_TARGET: StandaloneWindows64
